modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/N3ROO/LatencyMod/issues"

[[mods]]
modId="latencymod"
version="0.1.0"
displayName="Latency Mod"
# updateJSONURL="http://myurl.me/"
displayURL="https://github.com/N3ROO/LatencyMod/"
# logoFile="examplemod.png"
# credits="someone"
authors="@N3ROO on github"
description='''
A simple mod that shows the latency (ping) of your minecraft client to the server you're currently playing on.
'''